### PR TITLE
Removing a console log

### PR DESCRIPTION
**Pull request by jonshaffer**
This is causing issues in a current projects Karma output, console.log got released with 1.0.8

Adding reference to #26

### CODE REVIEW

**Comment by vort3xxx** [comment]
http://imgur.com/a/bAG1t

**Comment by juanpablob** [comment]
Why are you using the development version instead of distribution (compiled) version? Last one doesn't have the `console.log`.

**Comment by jonshaffer** [comment]
Here is the usage:

```
import 'angular-environment';
```

It looks like that will bring in the development version via `/index.js`. Should I be doing something different when consuming from an es6 app that does not remove console.log's on compile?

**Comment by daleyjem** [comment]
Does it need to be there in the first place? Why not allow an Angular provider configuration if you want to include any debugging options?

**Comment by kennydifiore** [comment]
@juanpablob The dist version _does_ have the console.log in it...

**Comment by juanpablob** [comment]
Thank you guys and sorry that this took so long for me to merge.

**Comment by kennydifiore** [comment]
@juanpablob Anxiously awaiting a new npm release!

**Pull request merged**
